name = "ghfetch"
main = "build/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "RATE_LIMIT_KV"
id = "f5068426dcbd42d8a907da7dbcd2b289"

[build]
command = "cargo install worker-build && worker-build --release --no-panic-recovery"
cwd = "."
